server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: discovery
              uri: http://localhost:8761
              predicates:
                - Path=/eureka/**,/
jwt:
  secret: 8d92f3f8c2d44a12b9c6e7a8d9e0f1128d92f3f8c2d44a12b9c6e7a8d9e0f11
