server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: discovery
              uri: lb://discovery-server
              predicates:
                - Path=/eureka/**

            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/auth/**

            - id: admin
              uri: lb://auth-service
              predicates:
                - Path=/admin/**

            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/users/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: 8d92f3f8c2d44a12b9c6e7a8d9e0f1128d92f3f8c2d44a12b9c6e7a8d9e0f11
