server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: discovery
          uri: lb://discovery-server
          predicates:
            - Path=/discovery,/discovery/**
          filters:
            - StripPrefix=1
