server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://192.168.20.45:5432/micro_service_test
    username: aslpgsql
    password: Ipsb@%$321
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: 8d92f3f8c2d44a12b9c6e7a8d9e0f1128d92f3f8c2d44a12b9c6e7a8d9e0f11
  access-expiration: 900000
  refresh-expiration: 604800000
