server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://192.168.20.45:5432/micro_service_test
    username: aslpgsql
    password: Ipsb@%$321
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000
  cache:
    type: redis
    redis:
      time-to-live: 600000   # 10 minutes

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    instances:
      authService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5

  timelimiter:
    instances:
      authService:
        timeoutDuration: 3s
