server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://192.168.20.45:5432/micro_service_test
    username: aslpgsql
    password: Ipsb@%$321
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
